# Generated by Django 5.1.7 on 2025-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bond",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("maturity", models.CharField(max_length=10)),
                ("yield_rate", models.DecimalField(decimal_places=4, max_digits=6)),
                (
                    "price_change_day",
                    models.DecimalField(decimal_places=4, max_digits=6),
                ),
                (
                    "percentage_week",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "percentage_month",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                (
                    "percentage_year",
                    models.DecimalField(decimal_places=4, max_digits=5),
                ),
                ("date", models.DateField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
