# Generated by Django 5.1.7 on 2025-03-30 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketdata", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bond",
            name="date",
        ),
    ]
